# Generated by Django 2.2.1 on 2020-02-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_auto_20200207_1504'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
