# Generated by Django 2.2.1 on 2020-02-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_auto_20200208_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
